/**
 * Environment bindings for watchlist service
 * Extends the types generated by wrangler types
 */
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		WATCHLIST_KV: KVNamespace;
		WATCHLIST_VECTORIZE: VectorizeIndex;
		AI?: {
			run: (
				model: string,
				input: { text: string[] },
			) => Promise<{ data: number[][] }>;
		};
		GROK_API_KEY?: string;
		/**
		 * Sentry DSN for error tracking.
		 * If not set, Sentry will be disabled.
		 */
		SENTRY_DSN?: string;
		/**
		 * Environment identifier (e.g., "dev", "production", "preview", "local").
		 */
		ENVIRONMENT?: string;
		/**
		 * Auth service binding for subscription checks
		 */
		AUTH_SERVICE?: Service;
		/**
		 * Thread service binding for creating and tracking threads
		 */
		THREAD_SVC?: Service;
		/**
		 * R2 Access Key ID for generating presigned URLs.
		 * Create via Cloudflare Dashboard > R2 > Manage R2 API Tokens
		 */
		R2_ACCESS_KEY_ID?: string;
		/**
		 * R2 Secret Access Key for generating presigned URLs.
		 * Create via Cloudflare Dashboard > R2 > Manage R2 API Tokens
		 */
		R2_SECRET_ACCESS_KEY?: string;
		/**
		 * Cloudflare Account ID for R2 endpoint URL.
		 * Find in Cloudflare Dashboard URL or Overview page.
		 */
		CLOUDFLARE_ACCOUNT_ID?: string;
		/**
		 * R2 bucket name (optional override).
		 * Defaults to bucket configured in wrangler.jsonc
		 */
		R2_BUCKET_NAME?: string;
	}
}
