/**
 * Environment bindings for watchlist service
 * Extends the types generated by wrangler types
 */
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		WATCHLIST_KV: KVNamespace;
		WATCHLIST_VECTORIZE: VectorizeIndex;
		AI?: {
			run: (
				model: string,
				input: { text: string[] },
			) => Promise<{ data: number[][] }>;
		};
		ADMIN_API_KEY?: string;
		GROK_API_KEY?: string;
	}
}
