import { ApiException, fromHono } from "chanfana";
import { Hono } from "hono";
import { ContentfulStatusCode } from "hono/utils/http-status";
import pkg from "../package.json";
import { getOpenApiInfo, getScalarHtml, type AppMeta } from "./app-meta";
import { HealthEndpoint } from "./endpoints/watchlist/health";
import { SearchEndpoint } from "./endpoints/watchlist/search";
import { TargetReadEndpoint } from "./endpoints/watchlist/targetRead";
import {
	IngestionRunsListEndpoint,
	IngestionRunReadEndpoint,
} from "./endpoints/watchlist/ingestionRuns";
import {
	AdminIngestEndpoint,
	AdminReindexEndpoint,
} from "./endpoints/watchlist/adminIngest";

// Start a Hono app
const app = new Hono<{ Bindings: Env }>();

const appMeta: AppMeta = {
	name: pkg.name,
	version: pkg.version,
	description: pkg.description,
};

app.onError((err, c) => {
	if (err instanceof ApiException) {
		// If it's a Chanfana ApiException, let Chanfana handle the response
		return c.json(
			{ success: false, errors: err.buildResponse() },
			err.status as ContentfulStatusCode,
		);
	}

	console.error("Global error handler caught:", err); // Log the error if it's not known

	// For other errors, return a generic 500 response
	return c.json(
		{
			success: false,
			errors: [{ code: 7000, message: "Internal Server Error" }],
		},
		500,
	);
});

// Setup OpenAPI registry
const openapi = fromHono(app, {
	// Keep the autogenerated docs available; serve Scalar at `/docsz`.
	docs_url: "/docs",
	schema: {
		info: getOpenApiInfo(appMeta),
	},
});

app.get("/", (c) => {
	if (c.req.header("x-force-error") === "1") {
		throw new Error("Forced error");
	}

	return c.json({ name: appMeta.name, version: appMeta.version });
});

app.get("/docsz", (c) => {
	return c.html(getScalarHtml(appMeta));
});

// Register watchlist endpoints
openapi.get("/healthz", HealthEndpoint);
openapi.post("/search", SearchEndpoint);
openapi.get("/targets/:id", TargetReadEndpoint);
openapi.get("/ingestion/runs", IngestionRunsListEndpoint);
openapi.get("/ingestion/runs/:runId", IngestionRunReadEndpoint);
openapi.post("/admin/ingest", AdminIngestEndpoint);
openapi.post("/admin/reindex", AdminReindexEndpoint);

// Export queue consumer for background ingestion processing
// Cloudflare Workers will automatically use this export for queue consumption
import queueConsumer from "./queue-consumer";
export const queue = queueConsumer.queue;

// Export the Hono app
export default app;
