import { ApiException, fromHono } from "chanfana";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { ContentfulStatusCode } from "hono/utils/http-status";
import * as Sentry from "@sentry/cloudflare";
import pkg from "../package.json";
import { getOpenApiInfo, getScalarHtml, type AppMeta } from "./app-meta";
import { authMiddleware, adminMiddleware } from "./lib/auth-middleware";
import { HealthEndpoint } from "./endpoints/watchlist/health";
import { SearchEndpoint } from "./endpoints/watchlist/search";
import { TargetReadEndpoint } from "./endpoints/watchlist/targetRead";
import {
	IngestionRunsListEndpoint,
	IngestionRunReadEndpoint,
} from "./endpoints/watchlist/ingestionRuns";
import { IngestionProgressEndpoint } from "./endpoints/watchlist/ingestionProgress";
import {
	AdminIngestEndpoint,
	AdminIngestSdnXmlEndpoint,
	AdminReindexEndpoint,
} from "./endpoints/watchlist/adminIngest";
import {
	IngestionStartEndpoint,
	IngestionCompleteEndpoint,
	IngestionFailedEndpoint,
} from "./endpoints/watchlist/ingestionUpload";
import { PepSearchEndpoint } from "./endpoints/watchlist/pepSearch";
import { uploadRoutes } from "./routes/upload";
import {
	InternalOfacTruncateEndpoint,
	InternalOfacBatchEndpoint,
	InternalOfacCompleteEndpoint,
	InternalOfacFailedEndpoint,
} from "./endpoints/watchlist/internalOfac";

/**
 * Extended environment bindings with Sentry support.
 */
export type Bindings = Env & {
	/**
	 * Cloudflare Worker version metadata.
	 * Used for Sentry release tracking.
	 */
	CF_VERSION_METADATA?: WorkerVersionMetadata;
	/**
	 * Sentry DSN for error tracking.
	 * If not set, Sentry will be disabled.
	 * Configured via Cloudflare Dashboard secrets or wrangler vars.
	 */
	SENTRY_DSN?: string;
	/**
	 * Environment identifier (e.g., "dev", "production").
	 */
	ENVIRONMENT?: string;
	/**
	 * Grok API key for AI-powered features.
	 */
	GROK_API_KEY?: string;
	/**
	 * R2 bucket for storing uploaded watchlist files (XML, etc.)
	 */
	WATCHLIST_UPLOADS_BUCKET?: R2Bucket;
	/**
	 * R2 Access Key ID for generating presigned URLs.
	 * Create via Cloudflare Dashboard > R2 > Manage R2 API Tokens
	 */
	R2_ACCESS_KEY_ID?: string;
	/**
	 * R2 Secret Access Key for generating presigned URLs.
	 * Create via Cloudflare Dashboard > R2 > Manage R2 API Tokens
	 */
	R2_SECRET_ACCESS_KEY?: string;
	/**
	 * Cloudflare Account ID for R2 endpoint URL.
	 * Find in Cloudflare Dashboard URL or Overview page.
	 */
	CLOUDFLARE_ACCOUNT_ID?: string;
	/**
	 * R2 bucket name (optional, defaults to 'watchlist-uploads').
	 * Override if using different bucket names per environment.
	 */
	R2_BUCKET_NAME?: string;
	/**
	 * Thread service binding for creating and tracking threads.
	 */
	THREAD_SVC?: Fetcher;
};

// Start a Hono app
const app = new Hono<{ Bindings: Bindings }>();

// Configure CORS to allow requests from configured domain subdomains
app.use(
	"*",
	cors({
		origin: (origin, c) => {
			// Get allowed domain from environment variable
			const allowedDomain = c.env.CORS_ALLOWED_DOMAIN;
			if (!allowedDomain) {
				// If no domain configured, allow all origins (for development)
				return "*";
			}

			if (!origin) return "*";

			try {
				const url = new URL(origin);
				const hostname = url.hostname;
				// Allow exact match
				if (hostname === allowedDomain) {
					return origin;
				}
				// Allow any subdomain (e.g., watchlist.janovix.workers.dev)
				if (hostname.endsWith(`.${allowedDomain}`)) {
					return origin;
				}
			} catch {
				// Invalid origin, deny
			}
			return null;
		},
		allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
		allowHeaders: [
			"Content-Type",
			"Authorization",
			"X-Requested-With",
			"Accept",
		],
		exposeHeaders: ["Content-Length", "Content-Type"],
		credentials: true,
	}),
);

const appMeta: AppMeta = {
	name: pkg.name,
	version: pkg.version,
	description: pkg.description,
};

app.onError((err, c) => {
	if (err instanceof ApiException) {
		// If it's a Chanfana ApiException, let Chanfana handle the response
		return c.json(
			{ success: false, errors: err.buildResponse() },
			err.status as ContentfulStatusCode,
		);
	}

	console.error("Global error handler caught:", err); // Log the error if it's not known

	// For other errors, return a generic 500 response
	return c.json(
		{
			success: false,
			errors: [{ code: 7000, message: "Internal Server Error" }],
		},
		500,
	);
});

// Setup OpenAPI registry
const openapi = fromHono(app, {
	// Keep the autogenerated docs available; serve Scalar at `/docsz`.
	docs_url: "/docs",
	schema: {
		info: getOpenApiInfo(appMeta),
	},
});

app.get("/", (c) => {
	if (c.req.header("x-force-error") === "1") {
		throw new Error("Forced error");
	}

	return c.json({ name: appMeta.name, version: appMeta.version });
});

app.get("/docsz", (c) => {
	return c.html(getScalarHtml(appMeta));
});

// Apply auth middleware to protected routes
// Pattern: Apply middleware to specific paths before registering endpoints
app.use("/search", authMiddleware());
app.use("/pep/search", authMiddleware());
app.use("/targets/*", authMiddleware());
//app.use("/ingestion/*", authMiddleware());

// Admin routes require authentication + admin role
app.use("/admin/*", authMiddleware());
app.use("/admin/*", adminMiddleware());
app.use("/api/upload/*", authMiddleware());
app.use("/api/upload/*", adminMiddleware());

// Register watchlist endpoints
openapi.get("/healthz", HealthEndpoint);
openapi.post("/search", SearchEndpoint);
openapi.post("/pep/search", PepSearchEndpoint);
openapi.get("/targets/:id", TargetReadEndpoint);
openapi.get("/ingestion/runs", IngestionRunsListEndpoint);
openapi.get("/ingestion/runs/:runId", IngestionRunReadEndpoint);
openapi.get("/ingestion/runs/:runId/progress", IngestionProgressEndpoint);
openapi.post("/ingestion/start", IngestionStartEndpoint);
openapi.post("/ingestion/:runId/complete", IngestionCompleteEndpoint);
openapi.post("/ingestion/:runId/failed", IngestionFailedEndpoint);
openapi.post("/admin/ingest", AdminIngestEndpoint);
openapi.post("/admin/ingest/sdn-xml", AdminIngestSdnXmlEndpoint);
openapi.post("/admin/reindex", AdminReindexEndpoint);

// Mount upload routes (for file uploads to R2)
app.route("/api/upload", uploadRoutes);

// Internal endpoints for container callbacks (no auth - secured via service binding)
openapi.post("/internal/ofac/truncate", InternalOfacTruncateEndpoint);
openapi.post("/internal/ofac/batch", InternalOfacBatchEndpoint);
openapi.post("/internal/ofac/complete", InternalOfacCompleteEndpoint);
openapi.post("/internal/ofac/failed", InternalOfacFailedEndpoint);

// Sentry is enabled only when SENTRY_DSN environment variable is set.
// Configure it via wrangler secrets: `wrangler secret put SENTRY_DSN`
export default Sentry.withSentry((env: Bindings) => {
	const versionId = env.CF_VERSION_METADATA?.id;
	return {
		// When DSN is undefined/empty, Sentry SDK is disabled (no events sent)
		dsn: env.SENTRY_DSN,
		release: versionId,
		environment: env.ENVIRONMENT,
		// Adds request headers and IP for users, for more info visit:
		// https://docs.sentry.io/platforms/javascript/guides/cloudflare/configuration/options/#sendDefaultPii
		sendDefaultPii: true,
	};
}, app);
