import { ApiException, fromHono } from "chanfana";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { ContentfulStatusCode } from "hono/utils/http-status";
import pkg from "../package.json";
import { getOpenApiInfo, getScalarHtml, type AppMeta } from "./app-meta";
import { HealthEndpoint } from "./endpoints/watchlist/health";
import { SearchEndpoint } from "./endpoints/watchlist/search";
import { TargetReadEndpoint } from "./endpoints/watchlist/targetRead";
import {
	IngestionRunsListEndpoint,
	IngestionRunReadEndpoint,
} from "./endpoints/watchlist/ingestionRuns";
import {
	AdminIngestEndpoint,
	AdminReindexEndpoint,
} from "./endpoints/watchlist/adminIngest";
import { PepSearchEndpoint } from "./endpoints/watchlist/pepSearch";
import { PepScreenEndpoint } from "./endpoints/pep/screen";
import { PepTestSearchEndpoint } from "./endpoints/pep/testSearch";
import { PepAnalyzeSearchEndpoint } from "./endpoints/pep/analyzeSearch";

// Start a Hono app
const app = new Hono<{ Bindings: Env }>();

// Configure CORS to allow requests from configured domain subdomains
app.use(
	"*",
	cors({
		origin: (origin, c) => {
			// Get allowed domain from environment variable
			const allowedDomain = c.env.CORS_ALLOWED_DOMAIN;
			if (!allowedDomain) {
				// If no domain configured, allow all origins (for development)
				return "*";
			}

			if (!origin) return "*";

			try {
				const url = new URL(origin);
				const hostname = url.hostname;
				// Allow exact match
				if (hostname === allowedDomain) {
					return origin;
				}
				// Allow any subdomain (e.g., watchlist.janovix.workers.dev)
				if (hostname.endsWith(`.${allowedDomain}`)) {
					return origin;
				}
			} catch {
				// Invalid origin, deny
			}
			return null;
		},
		allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
		allowHeaders: [
			"Content-Type",
			"Authorization",
			"X-Requested-With",
			"Accept",
		],
		exposeHeaders: ["Content-Length", "Content-Type"],
		credentials: true,
	}),
);

const appMeta: AppMeta = {
	name: pkg.name,
	version: pkg.version,
	description: pkg.description,
};

app.onError((err, c) => {
	if (err instanceof ApiException) {
		// If it's a Chanfana ApiException, let Chanfana handle the response
		return c.json(
			{ success: false, errors: err.buildResponse() },
			err.status as ContentfulStatusCode,
		);
	}

	console.error("Global error handler caught:", err); // Log the error if it's not known

	// For other errors, return a generic 500 response
	return c.json(
		{
			success: false,
			errors: [{ code: 7000, message: "Internal Server Error" }],
		},
		500,
	);
});

// Setup OpenAPI registry
const openapi = fromHono(app, {
	// Keep the autogenerated docs available; serve Scalar at `/docsz`.
	docs_url: "/docs",
	schema: {
		info: getOpenApiInfo(appMeta),
	},
});

app.get("/", (c) => {
	if (c.req.header("x-force-error") === "1") {
		throw new Error("Forced error");
	}

	return c.json({ name: appMeta.name, version: appMeta.version });
});

app.get("/docsz", (c) => {
	return c.html(getScalarHtml(appMeta));
});

// Register watchlist endpoints
openapi.get("/healthz", HealthEndpoint);
openapi.post("/search", SearchEndpoint);
openapi.post("/pep/search", PepSearchEndpoint);
openapi.post("/pep/screen", PepScreenEndpoint);
openapi.post("/pep/test-search", PepTestSearchEndpoint);
openapi.post("/pep/analyze-search", PepAnalyzeSearchEndpoint);
openapi.get("/targets/:id", TargetReadEndpoint);
openapi.get("/ingestion/runs", IngestionRunsListEndpoint);
openapi.get("/ingestion/runs/:runId", IngestionRunReadEndpoint);
openapi.post("/admin/ingest", AdminIngestEndpoint);
openapi.post("/admin/reindex", AdminReindexEndpoint);

// Export the Hono app
export default app;
